<?php
// src/pages/galerie.php
//
// The grid is built from public/img/gallery/manifest.json, which is
// regenerated by `npm run build:gallery` (scripts/build-gallery.js)
// straight from whatever original photos sit in assets/gallery-originals/.
// Drop a new photo in that folder, re-run the script, and it shows up here —
// this page itself never needs to change.

$manifestPath = __DIR__ . '/../../public/img/gallery/manifest.json';
$photos = [];
if (is_file($manifestPath)) {
    $decoded = json_decode(file_get_contents($manifestPath), true);
    if (is_array($decoded)) {
        $photos = $decoded;
    }
}
?>
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Galerie photo du Tennis-Club Dardagny : tournois, cours et moments de club.">
    <title>Galerie - TC Dardagny</title>
    <link rel="canonical" href="/galerie">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/galerie.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="theme-color" content="#1a3150">
    <link rel="icon" href="/img/favicon.ico" type="image/x-icon">
</head>

<body>
    <?php include __DIR__ . '/../includes/header.php'; ?>
    <main style="opacity: 0;">
        <div class="titre">
            <h1>Galerie</h1>
            <h2>Tournois, cours et moments de club</h2>
        </div>

        <?php if (empty($photos)): ?>
            <p class="gallery-empty">Aucune photo pour le moment.</p>
        <?php else: ?>
            <div class="gallery-grid">
                <?php foreach ($photos as $index => $photo):
                    $thumb = htmlspecialchars($photo['thumb'] ?? '', ENT_QUOTES, 'UTF-8');
                    $full = htmlspecialchars($photo['full'] ?? '', ENT_QUOTES, 'UTF-8');
                    $width = (int) ($photo['width'] ?? 0);
                    $height = (int) ($photo['height'] ?? 0);
                    $alt = htmlspecialchars($photo['alt'] ?? '', ENT_QUOTES, 'UTF-8');
                ?>
                    <button type="button" class="gallery-item"
                        data-full="<?php echo $full; ?>"
                        data-width="<?php echo $width; ?>"
                        data-height="<?php echo $height; ?>"
                        data-alt="<?php echo $alt; ?>">
                        <img src="<?php echo $thumb; ?>" alt="<?php echo $alt; ?>"
                            width="<?php echo $width; ?>" height="<?php echo $height; ?>"
                            loading="<?php echo $index < 8 ? 'eager' : 'lazy'; ?>" decoding="async">
                    </button>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <div class="gallery-lightbox" id="gallery-lightbox" aria-hidden="true">
            <div class="gallery-lightbox-backdrop"></div>
            <button type="button" class="gallery-lightbox-close" aria-label="Fermer la photo">
                <i class="fa fa-times" aria-hidden="true"></i>
            </button>
            <div class="gallery-lightbox-frame">
                <img class="gallery-lightbox-img" src="" alt="" draggable="false">
            </div>
        </div>
    </main>
    <?php $page_scripts = ['galerie.js']; include __DIR__ . '/../includes/footer.php'; ?>
</body>

</html>
